import type { NextApiRequest, NextApiResponse } from 'next';
import { AgentConfig, getAgents } from '../../lib/loadPrompts';

// This would ideally be imported from a shared location if used elsewhere,
// or generated by a script if it must originate from Python.
const AGENT_NAMES = [
  "Id",
  "Eros (Life Drive)",
  "Thanatos (Death Drive)",
  "Ego",
  "Defence Manager",
  "Conscience",
  "Ego-Ideal",
  "Imaginary Register",
  "Symbolic Register",
  "Real Register",
  "objet petit a",
  "Sinthome",
  "Discourse of the Master",
  "Discourse of the University",
  "Discourse of the Hysteric",
  "Discourse of the Analyst"
];

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<AgentConfig[] | { error: string }>
) {
  if (req.method === 'GET') {
    try {
      const agents = getAgents();
      res.status(200).json(agents);
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      console.error("Error in /api/agents:", errorMessage, error);
      res.status(500).json({ error: `Failed to load agent configurations. ${errorMessage}` });
    }
  } else {
    res.setHeader('Allow', ['GET']);
    res.status(405).end(`Method ${req.method} Not Allowed`);
  }
} 