import React from 'react';
import {
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogDescription, 
  DialogFooter 
} from "@/components/ui/dialog"; // Assuming this is where your ShadCN/Radix dialog is exported
import { Button } from "@/components/ui/button";
import Link from 'next/link';

interface InfoModalProps {
  onClose: () => void;
}

const InfoModal: React.FC<InfoModalProps> = ({ onClose }) => {
  return (
    <Dialog open={true} onOpenChange={(isOpen) => !isOpen && onClose()}>
      <DialogContent className="bg-gray-800 text-gray-100 border-gray-700 sm:max-w-[525px]">
        <DialogHeader>
          <DialogTitle className="text-purple-400 text-xl">About Mind Theatre</DialogTitle>
          <DialogDescription className="text-gray-300 pt-2 text-sm">
            Mind Theatre is a multi-agent chatbot simulating a Freudian-Lacanian mind. 
            Each psychic component (Id, Ego, Superego, etc.) is an independent AI agent. 
            A Synthesiser agent integrates these inner voices to form a coherent reply.
          </DialogDescription>
        </DialogHeader>
        <div className="py-4 text-gray-200 text-sm space-y-3">
          <p>
            This project explores the complexities of simulated consciousness and artificial psychology.
            It aims to provide an observable emotional landscape generated by the interactions of these AI agents.
          </p>
          <div>
            <p className="font-semibold mb-1 text-purple-300">Project Status: BETA</p>
            <p className="mb-1">
              Mind Theatre is currently in beta. It is a working experiment and an ongoing exploration into AI behavior and interaction.
              As such, you may encounter unexpected responses or behaviors. 
            </p>
            <p>
              Feedback is welcome and appreciated! Please send your thoughts, suggestions, or any issues encountered to: {' '}
              <a href="mailto:jove@spucchi.com" className="text-blue-400 hover:text-blue-300 underline">
                jove@spucchi.com
              </a>.
            </p>
          </div>
          <div>
            <p className="font-semibold mb-1 text-purple-300">Discover more:</p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li>
                <Link href="https://spucchi.com" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300 underline">
                  spucchi.com
                </Link> - Creative & Technical Portfolio
              </li>
              <li>
                <Link href="https://opertus.systems" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300 underline">
                  opertus.systems
                </Link> - AI & Systems Development
              </li>
              <li>
                <Link href="https://jov3.com" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300 underline">
                  jov3.com
                </Link> - Personal Site
              </li>
            </ul>
          </div>
        </div>
        <DialogFooter>
          <Button onClick={onClose} className="bg-purple-600 hover:bg-purple-700 text-white">
            Close
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default InfoModal; 