export const AGENTS = [
  { name: 'Id', prompt: '' },
  { name: 'Eros (Life Drive)', prompt: '' },
  { name: 'Thanatos (Death Drive)', prompt: '' },
  { name: 'Ego', prompt: '' },
  { name: 'Defence Manager', prompt: '' },
  { name: 'Conscience', prompt: '' },
  { name: 'Ego-Ideal', prompt: '' },
  { name: 'Imaginary Register', prompt: '' },
  { name: 'Symbolic Register', prompt: '' },
  { name: 'Real Register', prompt: '' },
  { name: 'objet petit a', prompt: '' },
  { name: 'Sinthome', prompt: '' },
  { name: 'Discourse of the Master', prompt: '' },
  { name: 'Discourse of the University', prompt: '' },
  { name: 'Discourse of the Hysteric', prompt: '' },
  { name: 'Discourse of the Analyst', prompt: '' },
  { name: 'System', prompt: '' },
  { name: 'Psyche', prompt: '' },
];

export const AGENT_COLORS: Record<string, string> = {
  'Id': 'red',
  'Eros (Life Drive)': 'deepPink',
  'Thanatos (Death Drive)': 'darkSlateBlue',
  'Ego': 'green',
  'Defence Manager': 'darkGoldenRod',
  'Conscience': 'orange',
  'Ego-Ideal': 'purple',
  'Imaginary Register': 'teal',
  'Symbolic Register': 'saddleBrown',
  'Real Register': 'gray',
  'objet petit a': 'olive',
  'Sinthome': 'maroon',
  'Discourse of the Master': 'navy',
  'Discourse of the University': 'darkCyan',
  'Discourse of the Hysteric': 'crimson',
  'Discourse of the Analyst': 'darkSlateGray',
  'System': 'black',
  'Psyche': 'magenta',
}; 